volumes:
  test_postgres_data:
  test_runner_data:

services:
  test_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_runner:
    image: fastapi:latest
    depends_on:
      test_db:
        condition: service_healthy
    command: tail -f /dev/null
    volumes:
      - .:/app
      - test_runner_data:/root/.cache
    environment:
      - ENVIRONMENT=test
