volumes:
  postgres_data:

services:
  fastapi:
    image: fastapi:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=docker

  nginx:
    # To have production-like setup
    image: nginx:1.25
    restart: unless-stopped
    depends_on:
      - fastapi
    ports:
      - "8000:80"
    volumes:
      - ./devops/nginx/local/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
