"""Initial Migration

Revision ID: 88a69c329979
Revises:
Create Date: 2025-06-28 17:29:55.599122

"""

import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88a69c329979"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("birth_year", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "film",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=True),
        sa.Column("director", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("producer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "starship",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("manufacturer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "characterfilmlink",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["film.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "film_id"),
    )
    op.create_table(
        "characterstarshiplink",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("starship_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["starship_id"],
            ["starship.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "starship_id"),
    )
    op.create_table(
        "starshipfilmlink",
        sa.Column("starship_id", sa.Integer(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["film.id"],
        ),
        sa.ForeignKeyConstraint(
            ["starship_id"],
            ["starship.id"],
        ),
        sa.PrimaryKeyConstraint("starship_id", "film_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("starshipfilmlink")
    op.drop_table("characterstarshiplink")
    op.drop_table("characterfilmlink")
    op.drop_table("starship")
    op.drop_table("film")
    op.drop_table("character")
    # ### end Alembic commands ###
